Code review 2 for Task02 - IP-Filter
mkvdv/otus-cpp-2018 pull request #2
Opened 2018-08-31 01:06 UTC by mkvdv

Welcome for code review!

2018-09-05 16:18 UTC, ithamsteri requested changes
Задание простое, но не с простой реализацией. Код трудно читать, везде `std::reference_wrapper`. Код можно упростить и сделать более читабельным. :eyeglasses:

2018-09-05 16:18 UTC, ithamsteri commented on .travis.yml
> +  - cmake ..
**Совет:** можно избавиться от ручного создания `build` каталога. Пример:
```
$ cmake -H. -Bbuild -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Release
```
где:
* `-H` указывает путь до CMake проекта;
* `-B` задаёт путь для каталога сборки (создаёт его, если нет его);
* `-D` задаёт переменные в CMake, что может добавить гибкости.

Далее:
```
$ cmake --build build
$ cmake --build build --target test
$ cmake --build build --target package
```

в результате будет deb-пакет в каталоге `build`.

2018-09-05 16:18 UTC, ithamsteri commented on CMakeLists.txt
> +    CXX_STANDARD 17
**Внимание:** CMake знает о
* C++14 стандарте только с версии `3.3`;
* C++17 стандарте только с версии `3.8`.

поэтому нужно выбрать минимально требуемую версию правильно.

2018-09-05 16:18 UTC, ithamsteri commented on CMakeLists.txt
> +execute_process(COMMAND git submodule update --init -- libs/gtest
**Замечание:** не стоит запускать данную команду в CMake. Лучше это сделать в `.travis.yml` или заранее при клонировании проекта:
```
git clone --recurse-submodules https://github.com/mkvdv/otus-cpp-2018
```

2018-09-05 16:18 UTC, ithamsteri commented on CMakeLists.txt
> +    COMPILE_OPTIONS -Wall -Wextra -Werror -Wpedantic -fsanitize=address
**Замечание:** не кросплатформенное решение. Нужно проверять используемый компилятор при ручном задании флагов компиляции:

```cmake
# set warning flags for popular compilers
function(set_warning_flags target)
        if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU" OR CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
                target_compile_options(${target} PRIVATE "-Wall" "-Wextra" "-pedantic-errors")
        elseif(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
                target_compile_options(${target} PRIVATE "/W4")
        endif()
endfunction()

set_warning_flags(ip_filter)
set_warning_flags(test_utils)
```

2018-09-05 16:18 UTC, ithamsteri commented on src/ip_filter.cpp
> +//#define DEBUG
**Совет:** при Release сборке CMake автоматически добавляет для всех компиляторов `NDEBUG`. Можно этим воспользоваться, также как пользуется заголовочный файл `<cassert>` :smirk: 
```cpp
#ifndef NDEBUG
    ...
#endif // NDEBUG
```

2018-09-05 16:18 UTC, ithamsteri commented on src/ip_filter.cpp
> +	const int ERR_CODE = -1;
**Совет:** можно задействовать [стандартную библиотеку](https://en.cppreference.com/w/cpp/utility/program/EXIT_status), используя заголовочный файл `<cstdlib>`:
```cpp
#include <cstdlib>

int main(int argc, char**) {
    if (argc < 2) {
        return EXIT_FAILURE;

    return EXIT_SUCCESS;
}
```

2018-09-05 16:18 UTC, ithamsteri commented on src/ip_filter.cpp
> +#ifdef DEBUG
**Вопрос:** а нужны ли эти секции с `DEBUG`? Они затрудняют чтение кода.
Есть же Unit Test'ы, чтобы удостовериться, что код выполняется правильно.

2018-09-05 16:18 UTC, ithamsteri commented on src/utils.h
> +	using ip_t = std::vector<std::byte>;
**Совет:** если известна длина массива и она фиксирована, то не целесообразно использовать `std::vector<std::byte>`, а лучше `std::array<std::byte, 4>`.

2018-09-05 16:18 UTC, ithamsteri commented on src/ip_filter.cpp
> +			   return std::lexicographical_compare(a.cbegin(), a.cend(),
Как-то мудрёно и не понятно получилось. Чем не понравилась обычная сортировка? Она тоже лексикографически правильной будет:
```cpp
std::sort(ip_pool.begin(), ip_pool.end(), std::greater<>());
```

2018-09-05 16:18 UTC, ithamsteri commented on src/utils.cpp
> +				cout << static_cast<unsigned >(*ip_part);
Вывод сделан очень хорошо. :+1: 
Может избавиться от постоянных преобразований типов, то `std::byte`, то `unsigned`. Выбрать один тип и хранить его в `ip_t`?

2018-09-05 16:18 UTC, ithamsteri commented on src/utils.cpp
> +	void print(const std::vector<std::reference_wrapper<const ip_t>> &ip_pool)
Сложные конструкции с `std::reference_wrapper`. Может упростить данный код?
**Совет:** Вывод можно сделать перегрузив `operator<<`:
```cpp
std::ostream &operator<<(std::ostream &os, const ip_t &ip);
```
затем будет более удобно использовать вывод:
```cpp
for (const ip_t &ip : ip_pool) {
    std::cout << ip << '\n';
}
```

2018-09-05 16:18 UTC, ithamsteri commented on src/utils.h
> +		constexpr T &&operator()(T &&t) const noexcept
Не понятно зачем нужна эта функциональная структура. Нужны комментарии, чтобы разобраться, что тут происходит :smiley:

2018-09-07 13:36 UTC, mkvdv commented on CMakeLists.txt
> +    CXX_STANDARD 17
Спасибо, не знал об этом раньше.

2018-09-07 15:20 UTC, mkvdv commented on src/ip_filter.cpp
> +			   return std::lexicographical_compare(a.cbegin(), a.cend(),
Действительно, не заметил, что для векторов реализованы операторы лексикографического сравнения, спасбо.

2018-09-09 11:21 UTC, mkvdv commented on CMakeLists.txt
> +execute_process(COMMAND git submodule update --init -- libs/gtest
> не стоит запускать данную команду в CMake

Почему Вы так считаете? Какими опасностями черевато включение данный комнады в `CMakeLists.txt`

2018-09-09 12:24 UTC, mkvdv commented on src/utils.cpp
> +	void print(const std::vector<std::reference_wrapper<const ip_t>> &ip_pool)
> Сложные конструкции с std::reference_wrapper. Может упростить данный код?

Вы предлагаете в принцпе не исползовать в коде `reference_wrapper`? К сожалению, не придумал других вариантов того, как вернуть отфильтрованные `ip_t` из функции, при этом не копируя сами `ip_t`. 

Возможно, это premature optimization, но зачем копировать много векторов, если можно просто вернуть ссылки на них в исходной структуре. Хотя можем получить висячую ссылку, но не хотелось в таком простом коде заморачиваться и об этом.

2018-09-09 12:35 UTC, mkvdv commented on src/utils.h
> +		constexpr T &&operator()(T &&t) const noexcept
Не уверен, но разве в месте определение структуры нужно комментировать те места и случаи, где она будет использоваться? 
Возможно, достаточно взглянуть на место её использования =)

И если бы на дворе был [2020 год](https://en.cppreference.com/w/cpp/utility/functional/identity), определение структуры не пришлось бы писать :smile:

2018-09-09 12:36 UTC, mkvdv commented
Благодарю за ревью, узнал много полезного.

2018-09-28 14:12 UTC, closed without merging